import Header from "@/components/Layout/Header";
import { ScrollWrapper } from "@/components/ScrollWrapper";
import "@/styles/index.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jet Seattle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <ScrollWrapper />
      </body>
    </html>
  );
}
